myproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
     re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.about),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name="list"),
    path('new-post/', views.post_new, name="new-post"),
    path('<slug:slug>/', views.post_page, name="page"),
    path('<slug:slug>/edit/', views.post_update, name="update"),
    path('<slug:slug>/delete/', views.post_delete, name="delete"),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True) # o blank permite não ter uma imagem
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django import forms
from . import models

class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'body', 'slug', 'banner']

myproject/views.py
#from django.http import HttpResponse
from django.shortcuts import render
def homepage(request):
    #return HttpResponse("Hello World! I'm Home.")
    return render(request, 'home.html')

def about(request):
    #return HttpResponse("Hello World! What about?")
    return render(request, 'about.html')

posts/views.py
from django.shortcuts import redirect, render
from .models import Post
from django.contrib.auth.decorators import login_required
from. import forms

def posts_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html', {'posts': posts})

def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html', {'post': post})

@login_required(login_url="/users/login/") # decorator checa se tá logado. Se não, ele redireciona para o login_url
def post_new(request):
    if request.method == 'POST':
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            newpost = form.save(commit=False)
            newpost.author = request.user
            newpost.save()
            return redirect('posts:list')
    else:
        form = forms.CreatePost()
    return render(request, 'posts/post_new.html', {'form': form})

def post_update(request, slug):
    post = Post.objects.get(slug=slug)
    if request.method == 'POST':
        form = forms.CreatePost(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:page', slug=post.slug)
    else:
        form = forms.CreatePost(instance=post)
    
    context = {
        'form': form,
        'post': post
    }
    return render(request, 'posts/post_update.html', context)

def post_delete(request, slug):
    post = Post.objects.get(slug=slug)
    if request.method == 'POST':
        post.delete()
    return redirect('posts:list')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout



def register_view(request):
    if request.method == "POST": #if the form is submited and is POST
        form = UserCreationForm(request.POST) # form recebe os dados
        if form.is_valid(): # verifica se é válido para salvar
            login(request, form.save()) # isso é para automaticamente logar o usuário ao registrar e com form.save() salvar no banco de dados
            return redirect("posts:list")
    else:
        form = UserCreationForm()

    return render(request, 'users/register.html', {"form": form})

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user()) # isso serve para logar
            if "next" in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("posts:list")
    else:
        form = AuthenticationForm()
    
    return render(request, 'users/login.html', {"form": form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("posts:list")

myproject/users/templates/users/login.html
{% extends 'layout.html' %}

{% block title %}
    User Login
{% endblock %}

{%  block content%}
    <section>
        <h1>User Login</h1>
        <form class="form-with-validation" action="{% 'users:login' %}" method="post">
            {% csrf_token %}
            {{ form }}
            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}" />
            {% endif %}
            <button class="form-submit">Submit</button>
        </form>
    </section>
{% endblock %}

myproject/users/templates/users/register.html
{% extends 'layout.html' %}

{% block title %}
    Register a New User
{% endblock %}

{%  block content%}
    <section>
        <h1>Register a New User</h1>
        <form class="form-with-validation" action="{% 'users:login' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <button class="form-submit">Submit</button>
        </form>
    </section>
{% endblock %}

posts/templates/posts/post_new.html
{% extends 'layout.html' %}

{% block title %}
    New Post
{% endblock %}

{%  block content%}
    <section>
        <h1>New Post</h1>
        <form class="form-with-validation" action="{% url 'posts:new-post' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <button class="form-submit">Add Post</button>
        </form>
    </section>
{% endblock %}

posts/templates/posts/post_page.html
{% extends 'layout.html' %}
{% load tz %} <!-- para adicionar a timezone na data do post -->

{% block title %}
    {{ post.title }}
{% endblock %}

{%  block content%}
    <section>
        <img 
        class="banner"
        src="{{ post.banner.url }}" 
        alt="{{ post.title }}"/>
        <h1>{{ post.title }}</h1>
        <p>{{ post.date|timezone:"America/Sao_Paulo"}}</p>
        <p>{{ post.body }}</p>
        
    </section>
{% endblock %}

posts/templates/posts/post_update.html
{% extends 'layout.html' %}

{% block title %}
    Edit Post
{% endblock %}

{%  block content%}
    <section>
        <h1>Edit Post</h1>
        <form class="form-with-validation" action="{% url 'posts:update' slug=post.slug%}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <button class="form-submit">Edit</button>
        </form>
    </section>
{% endblock %}

posts/templates/posts/posts_list.html
{% extends 'layout.html' %}
{% load tz %} <!-- para adicionar a timezone na data do post -->
{% block title %}
    Posts
{% endblock %}

{%  block content%}
    <section>
        <h1>Posts</h1>

        {% for post in posts %}
            <article class="post">
                <h2>
                    <a href="{% url 'posts:page' slug=post.slug %}">
                    {{ post.title }}
                    </a>
                </h2>
                <p>{{ post.date|timezone:"America/Sao_Paulo" }} by {{ post.author }}</p>
                <p>{{ post.body }}</p>
                {% if post.author == request.user %}
                    <div style="display: flex; gap: 10px; align-items: center;">
                        <!-- Update -->
                        <a href="{% url 'posts:update' slug=post.slug %}">
                            <button class="form-submit">Update Post</button>
                        </a>

                        <!-- Delete -->
                        <div id="delete-section">
                            <button id="show-confirm" class="form-submit">Delete Post</button>
                        </div>
                    </div>

                    <!-- Confirmação de delete (linha abaixo) -->
                    <div id="confirm-delete" style="display:none; margin-top:5px;">
                        <p><span>Tem certeza que quer deletar?</span></p>
                        <form action="{% url 'posts:delete' slug=post.slug %}" method="post" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="form-submit">Sim</button>
                        </form>
                        <button id="cancel-delete" class="form-submit">Não</button>
                    </div>

                    <script>
                        const showConfirm = document.getElementById('show-confirm');
                        const confirmDelete = document.getElementById('confirm-delete');
                        const cancelDelete = document.getElementById('cancel-delete');
                        
                        

                        showConfirm.addEventListener('click', () => {
                            showConfirm.style.display = 'none';
                            confirmDelete.style.display = 'block'; // aparece na linha de baixo
                        });

                        cancelDelete.addEventListener('click', () => {
                            showConfirm.style.display = 'inline';
                            confirmDelete.style.display = 'none';
                        });
                    </script>
                {% endif %}


            </article>
        {% endfor %}
    </section>
{% endblock %}

templates/about.html
{% extends 'layout.html' %}

{% block title %}
    About
{% endblock %}

{%  block content%}
    <h1>About</h1>
    <p>Check out my <a href="/">Home</a> page.</p>
{% endblock %}

templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock %}

{%  block content%}
    <h1>Home</h1>
    <p>Check out my <a href="/about">About</a> page.</p>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
     <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
    <nav>
        <a href="/" title="Home">
            <span role="img" aria-label="Home">🏠</span>
        </a> |
        <a href="/about" title="About">
            <span role="img" aria-label="About">😀</span>
        </a> |
        <a href="{% url 'posts:list' %}" title="Posts">
            <span role="img" aria-label="Posts">📰</span>
        </a> |
        {% if user.is_authenticated %}
        <a href="{% url 'posts:new-post' %}" title="New Post">
            <span role="img" aria-label="New Post"></span>🆕
            </a> |
            <form class="logout" action="{% url 'users:logout' %}" method="post">
                {% csrf_token %}
                <button class="logout-button" arial-label="User Logout" title="User Logout">👋</button>
            </form>
        {% else %}
            <a href="{% url 'users:register' %}" title="User Registration">
                <span role="img" aria-label="User Registration">👤</span>
            </a> |
            <a href="{% url 'users:login' %}" title="User Login">
                <span role="img" aria-label="User Login">🔐</span>
            </a>
        {% endif %}
            

    </nav>
    <main>
        {% block  content %}
        {% endblock  %}
    </main>
</body>
</html>

users/templates/users/login.html
{% extends 'layout.html' %}

{% block title %}
    User Login
{% endblock %}

{%  block content%}
    <section>
        <h1>User Login</h1>
        <form class="form-with-validation" action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            {{ form }}
            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}" />
            {% endif %}
            <button class="form-submit">Submit</button>
        </form>
    </section>
{% endblock %}

users/templates/users/register.html
{% extends 'layout.html' %}

{% block title %}
    Register a New User
{% endblock %}

{%  block content%}
    <section>
        <h1>Register a New User</h1>
        <form class="form-with-validation" action="{% url 'users:register' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <button class="form-submit">Submit</button>
        </form>
    </section>
{% endblock %}